//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class modulo
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public modulo()
    {
        this.operaciones = new HashSet<operaciones>();
    }

    public int id { get; set; }
    public string nombre { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<operaciones> operaciones { get; set; }
}

public partial class operaciones
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public operaciones()
    {
        this.rol_operacion = new HashSet<rol_operacion>();
    }

    public int id { get; set; }
    public string nombre { get; set; }
    public Nullable<int> idModulo { get; set; }

    public virtual modulo modulo { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<rol_operacion> rol_operacion { get; set; }
}

public partial class rol
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public rol()
    {
        this.rol_operacion = new HashSet<rol_operacion>();
        this.usuario = new HashSet<usuario>();
    }

    public int id { get; set; }
    public string nombre { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<rol_operacion> rol_operacion { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<usuario> usuario { get; set; }
}

public partial class rol_operacion
{
    public int id { get; set; }
    public Nullable<int> idRol { get; set; }
    public Nullable<int> idOperacion { get; set; }

    public virtual operaciones operaciones { get; set; }
    public virtual rol rol { get; set; }
}

public partial class usuario
{
    public int id { get; set; }
    public string nombre { get; set; }
    public string email { get; set; }
    public string password { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public Nullable<int> idRol { get; set; }
    public string PropiedadNueva { get; set; }

    public virtual rol rol { get; set; }
}
